### PR TITLE
Updated OpenSSL links

### PR DESCRIPTION
**Pull request by laggingreflex**
Updated broken OpenSSL for Windows binary links
Add other sources for getting binaries

### CODE REVIEW

**Comment by barrysteyn** [comment]
Why is this necessary? From version 6.0 onwards, there is no need for using OpenSSL.

**Comment by laggingreflex** [comment]
Oh I didn't notice that. I was on a project with older version (5.4.1). 
I'll upgrade to 6 then. So never mind I guess..

**Comment by mehcode** [comment]
@barrysteyn Then why is it still on the Readme? :smile_cat:

**Comment by barrysteyn** [comment]
@mehcode You are right, it shouldn't be there. I will remove the section...

**Comment by laggingreflex** [comment]
For context, I inherited a project that used this as a dependency, and me being the only one of the devs on Windows, the error I was getting was something like this:
```
module.js:485
 process.dlopen(filename, module.exports);
 ^
 Error: The specified module could not be found.
```
which didn't make it immediately obvious that it was due to lack of OpenSSL on windows. I had to come across [this](https://github.com/nodejs/node/issues/2964#issuecomment-152210141) to figure it all out. Only then I visited scrypt repo to find the same info which undeniably confirmed it. 
For that reason I think we should leave a little bit of info about OpenSSL on Windows specially pertaining to users coming from/for v5. I know it does say "there is no need to use an external OpenSSL library anymore" but maybe making OpenSSL bold, or even reiterating that v5 used to use OpenSSL and you should either upgrade to v6 or something like that?

**Pull request closed without merging**
